config/routes.rb
CourseProject::Application.routes.draw do
  
  ActiveAdmin.routes(self)


  #namespace :api, defaults: {format: 'json'} do
  #  namespace :v1 do
  #  	resources :users
  #  	resources :userdetails do
  #      post "userdetails/button_action"
  #    end  
  #  end
  #end

  root to: "main#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path => 'accounts'
  
  match "info" => "main#info"
  match "faq" => "main#faq"

  match "client" => "main#client"
  
  resources :userdetails do
    post "button_action"
    post "send_mail"
  end  
  resources :main, only: [:new]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  
  has_one :userdetail
  devise :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :admin, :userdetail_attributes
  
end

app/models/userdetail.rb
class Userdetail < ActiveRecord::Base

	belongs_to :user
	attr_accessible :firstname, :lastname, :url, :passcode, :user_id, :device_id
	validates :firstname, :lastname, presence: true

end

app/controllers/api/v1/userdetails_controller.rb
module Api

  module V1
  	
    class UserdetailsController < ApplicationController
    	respond_to :json
    	def index
    		respond_with Userdetail.all
    	end

    	def show
    		respond_with Userdetail.find(params[:id])
    	end

    	def button_action
    		value = params[:value]
    		@userdetail = Userdetail.find(params[:id])
    		curl @userdetail.url + "?value=" + value	
    	end

    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
	def index

		if user_signed_in?
			if current_user.userdetail.nil? 
				@userdetail = Userdetail.new
				redirect_to new_userdetail_path
			else
				@userdetail = current_user.userdetail
			end
		end
	end

	def info
		render :layout => "static"
	end

	def faq
		render :layout => "static"
	end

	def new

	end

	def client
		if (!User.find_by_id(params[:user_id]).nil? && params[:passcode].length > 0)
			@user = User.find(params[:user_id])
			#@passcode = params[:passcode]
			#if @user.userdetail.passcode.to_i == passcode.to_i
				redirect_to userdetail_path(@user.userdetail, :passcode => params[:passcode])
			#else
			#	redirect_to info_path, notice: "You don't have access to it client1"
			#end	
		else
			redirect_to info_path, notice: "Please enter correct profile ID / Password."
		end	
		
	end

end

app/controllers/userdetails_controller.rb
class UserdetailsController < ApplicationController
	require 'rest_client'
	layout 'application', :only => [:new, :create, :update]

	def new
		@userdetail = Userdetail.new	
	end

	def create
		@userdetail = Userdetail.new(params[:userdetail])
		@userdetail.user = current_user
		@userdetail.passcode = rand(11111...99999)
		if @userdetail.save
			redirect_to root_path, notice: "Updated Successfully"
		else
			render	"new"
		end	
	end

	def update
		@user = current_user
		@userdetail = @user.userdetail
		@userdetail.passcode = rand(11111...99999)

		if @userdetail.update_attributes(params[:userdetail])
			redirect_to root_path, notice: "Updated successfully"
		else
			render "edit", error: "There might be some problem updating it now"
		end	

	end

	def show
		@userdetail = Userdetail.find(params[:id])
		@user = @userdetail.user
		
		#if params.has_key?(:one)
			if params[:passcode].to_i != @userdetail.passcode.to_i
				redirect_to info_path, notice: "Sorry, you don't have access to it."	
			else
				render :layout => "special"
			end
		# else
		# 	if params[:passcode].to_i != @userdetail.passcode.to_i
		# 		redirect_to info_path, notice: "You don't have access to it from client"
		# 	else	
		# 		render :layout => "special"
		# 	end	
		#end		

	end

	def index		
		@userdetails = Userdetail.all
		respond_to do |format|
    		format.html
    		format.json { render json: @userdetails }
  		end
	end

	def button_action
		@userdetail = Userdetail.find(params[:userdetail_id])
		@value = params[:value]
		url = @userdetail.url + '?value=' + @value
    	#response = RestClient.get @userdetail.url, {'value' => @value}
    	RestClient.get url
    end

    def send_mail
    	email_id = params[:email]
		@userdetail = Userdetail.find(params[:userdetail_id])
		#@user_url = userdetail_url(@userdetail) + "?passcode=" + @userdetail.passcode.to_s
		if email_id != ""
    		UserMailer.send_dildoaccess(email_id, @userdetail).deliver
    		redirect_to root_path, notice: "Email has been sent"	
    	else	
    		redirect_to root_path, :flash => { :error => "Please type correct email!" }
    	end		
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def active(page)
		return 'class="active"'.html_safe if current_page?(page)
	end
	
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
 
<!-- Be sure to leave the brand out there if you want it shown -->
<%= link_to "edildo.me", root_path, :class => 'brand' %>
 
<!-- Everything you want hidden at 940px or less, place within here -->
<div class="nav-collapse collapse">
<!-- .nav, .navbar-search, .navbar-form, etc -->
  <ul class="nav">

    <li <%= active(root_path) %> ><%= link_to "Home", root_path %></li>
    <% if user_signed_in? %>
      <li <%= active(edit_user_registration_path) %>>
        <%= link_to('Edit credentials', edit_user_registration_path) %>
       </li>

      <li>
        <p class="navbar-text">Welcome <%= current_user.email %>, Not you? <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></p>
      </li>

    <% else %>
      <li <%= active(new_user_session_path)%> >
        <%= link_to('Model Login', new_user_session_path)  %>
      </li>
      <li <%= active(new_user_registration_path)%> >
          <%= link_to('Model Sign up', new_user_registration_path)  %>
      </li>
      <li <%= active(new_main_path)%> >
          <%= link_to('Customer Access', new_main_path)  %>
      </li>
    <% end %>
  </ul>

  <!--<ul class="nav pull-right">
    <li <%= active(new_user_session_path)%> >
        <%= link_to('Power User', new_user_session_path)  %>
    </li>
  </ul>-->

</div>

app/views/layouts/_specialnavigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
 
<!-- Be sure to leave the brand out there if you want it shown -->
<%= link_to "edildo.me", root_path, :class => 'brand' %>
 
<!-- Everything you want hidden at 940px or less, place within here -->
<div class="nav-collapse collapse">
<!-- .nav, .navbar-search, .navbar-form, etc -->
  <ul class="nav">

      <li>
        <p class="navbar-text">Welcome to Samantha's teledildonics site! Enjoy remote sex with <%= @userdetail.firstname + " " + @userdetail.lastname %></p>
      </li>
  </ul>

</div>

app/views/layouts/_staticnavigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
 
<!-- Be sure to leave the brand out there if you want it shown -->
<%= link_to "edildo.me", root_path, :class => 'brand' %>
 
<!-- Everything you want hidden at 940px or less, place within here -->
<div class="nav-collapse collapse">
<!-- .nav, .navbar-search, .navbar-form, etc -->
  <ul class="nav">

      <li>
        <p class="navbar-text">Welcome to Samantha's teledildonics site. Enjoy remote sex!</p>
      </li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Samantha's teledildonics site" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <br/><br/><br/>
            &copy; <a href='http://sexybirthdaywishes.com/robotic_interface/'>Sexy-birthday-wishes</a> <%= Time.now.year %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/special.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Samantha's teledildonics site" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="refresh" content="120"> 
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/specialnavigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <br/><br/><br/>
            &copy; <a href='http://sexybirthdaywishes.com/robotic_interface/'>Sexy-birthday-wishes</a> <%= Time.now.year %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/static.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Samantha's teledildonics site" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/staticnavigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <br/><br/><br/>
            &copy; <a href='http://sexybirthdaywishes.com/robotic_interface/'>Sexy-birthday-wishes</a> <%= Time.now.year %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/main/backup_index.html.erb
<h2>Welcome to the world of Robotics and personal desire</h2>


<% if !user_signed_in? %>
	Please <%= link_to('Login', new_user_session_path) %> to be able to access your device.
<% else %>
	
	<% if false %>
		DEMO BUTTON:
		<span title="send-signal">	
				<%= link_to ("https://api.electricimp.com/v1/edcb0ff950abe7e1/30432d1112005b3b"), :params["#FFxx"], method: :post  do %>	
					<div class="btn btn-large disabled" disabled="disabled"><i class="icon-heart"></i></div>
				<% end %>
		</span>	<br/><br/>

		<% if current_user.admin? %>
		<div class="well well-small">
			Tapan's circuit verification(Tapan's Node)<br/><br/>
			<%= button_to('#FF09 input', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab?value=#FF09', :method => "post", :remote => true, :disable_with => 'loading...') %>	
			<%= button_to('#FF01 input', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab?value=#FF01', :method => "post", :remote => true, :disable_with => 'loading...') %>	
		</div>
		<div class="well well-small">	
			Normal http verification by displaying data(Srijon's node)<br/>
			<%= button_to('On', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/30432d1112005b3b?value=1', :method => "post", :remote => true, :disable_with => 'loading...') %>	
			<%= button_to('Off', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/30432d1112005b3b?value=0', :method => "post", :remote => true, :disable_with => 'loading...') %>	
		</div>
		<div class="well well-small">	
			http verification by displaying data(Srijon's 2nd node with #FF09 & #FF01 as input)<br/>
			url:https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab<br/>
			<%= button_to('#FF09 input', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab?value=#FF09', :method => "post", :remote => true, :disable_with => 'loading...') %>	
			<%= button_to('#FF01 input', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab?value=#FF01', :method => "post", :remote => true, :disable_with => 'loading...') %>	
		</div>
		<div class="well well-small">	
			http verification by displaying data(Srijon's 2nd node with 0 & 1 as input)<br/>
			url:https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab<br/>
			<%= button_to('On', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab?value=1', :method => "post", :remote => true, :disable_with => 'loading...') %>	
			<%= button_to('Off', 'https://api.electricimp.com/v1/edcb0ff950abe7e1/3049cbfc815a4aab?value=0', :method => "post", :remote => true, :disable_with => 'loading...') %>	
		</div>
		<% else %>
			Please wait for the model to allow you...
		<% end %>	
	<% end %>
<% end %>	

app/views/main/faq.html.erb
faq

app/views/main/index.html.erb
<div class="well well-large"><h2>Welcome to Samantha's teledildonics site</h2></div>

<% if !user_signed_in? %>
	<br/><br/>
	<div class="row-fluid">
		<div class="span4 button_text"><%= link_to('<button class="btn btn-large btn-block" type="button">Model Login</button>'.html_safe, new_user_session_path) %></div>
		<!--<div class="span4 offset4 button_text"><%= link_to('<button class="btn btn-large btn-block btn-primary" type="button">Customer Access</button>'.html_safe, new_main_path) %></div>-->
	</div>	

<% else %>
	<% if @userdetail.url == "" %>
		Please give us some time to update your device url.
	<% else %>
		
		<div class="well well-small test-link">
			<%= link_to userdetail_url(@userdetail) + "?passcode=" + @userdetail.passcode.to_s, target: "_blank"  do%>	
				<span class="btn btn-custom"><i class="icon-hand-right"></i> ***CLICK HERE TO TEST YOUR LINK!*** <i class="icon-hand-left"></i></span>
			<% end %>	
		</div>
			

		<div class="well well-small">
			<h3>Sharing link with your partner:</h3> <!--<a href="#myModal" role="button" class="btn btn-primary" data-toggle="modal">Send link via email</a>

			<div id="myModal" class="modal hide fade active" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    <div class="modal-header">
		      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		      <h3 id="myModalLabel">Type Email:</h3>
		    </div>
		    
		    <%= form_tag userdetail_send_mail_path(@userdetail) do %>
		      <div class="modal-body">
		        <p><%= label_tag(:email, "Enter Email ID of the Customer:") %>
		          <%= text_field_tag(:email) %></p>
		      </div>
		      <div class="modal-footer">
		        <button class="btn btn-large btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
		          <%= submit_tag "Send", class: 'btn btn-large btn-primary'%>
		      </div>
		    <% end %>
		</div>-->

			Active link:<br/> <%= url_field_tag 'Active URL', nil , :value => userdetail_url(@userdetail) + "?passcode=" + @userdetail.passcode.to_s, :class => "span6", :onclick => 'this.select();' %> <small>(Click inside and  <cite title="Ctrl+C">Ctrl+C</cite> to copy the link)</small>
			<br/>	
			<div class="accordion" id="accordion2">
			  <div class="accordion-group">
			    <!--<div class="accordion-heading">-->
			      <button class="accordion-toggle btn btn-primary" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
			        Send above link by email: <i class="icon-chevron-down"></i>
			      </button>
			    <!--</div>-->
			    <div id="collapseOne" class="accordion-body collapse">
			      <div class="accordion-inner">
			        <%= form_tag userdetail_send_mail_path(@userdetail) do %>
					      
					        <%= label_tag(:email, "Enter Email ID of your partner:") %>
					        <%= text_field_tag(:email) %><br/>
					        <%= submit_tag "Send", class: 'btn btn-primary'%>
					      
					 <% end %>
			      </div>
			    </div>
			  </div>
			</div>
			<!--Click <%= link_to "here",  userdetail_url(@userdetail) + "?passcode=" + @userdetail.passcode.to_s, target: "_blank" %> to test the active link.-->
		</div>
		
		<!--<div class="text-center">OR</div>

		<div class="well well-small">
			<h3>Sharing details for client access:</h3>
			If you can not share the link above...<br/>
			Then ask the client to visit <strong><cite title="www.edildo.me">www.edildo.me</cite></strong> and click <strong>Client Access</strong><br/>
			(Share the below details to your client)<br/>
			Your Profile ID : <%= url_field_tag 'Profile ID', nil , :value => @userdetail.user.id, :class => "span1", :onclick => 'this.select();' %><br/>
			Your passcode: <%= url_field_tag 'Passcode', nil , :value => @userdetail.passcode, :class => "span1", :onclick => 'this.select();' %><br/>
			
		</div>-->
	
		<div class="well well-small">
			<h3>Regenerate the Link:</h3>
			To ensure privacy of your device, please click on <strong>regenerate</strong> button after you have completed a hot session with your partner. <br/><br/>

			<%= form_for @userdetail, :method => :put do |f| %>
		 		<%= f.submit "Regenerate Link", class: "btn btn-large btn-primary btn-danger" %>
			<% end %>
		</div>
			
		<div class="well well-small">
			<h3>Info:</h3>
			It is important to click the <strong>Regenerate Link</strong> button everytime a hot session is completed. This ensures that your partner is not accessing your device anymore.
		</div>

	<% end %>
<% end %>	

app/views/main/info.html.erb
<div class="well well-large">
Your access has been terminated<br/>
Request again<br/>


Share your experience...

</div>

app/views/main/new.html.erb
<div class="well well-large">
welcome to the world of sex toys<br/><br/>

<div class="alert alert-info">	
	Please ask the model to share her profile ID and passcode from her screen.<br/>
	Still confused! Watch this demonstration video.
</div>	

<%= form_tag(controller: "main", action: "client", method: "get") do %>
  <%= label_tag(:user_id, "Enter Profile ID of the Model:") %>
  <%= text_field_tag(:user_id) %>
  <%= label_tag(:passcode, "Enter the passcode:") %>
  <%= text_field_tag(:passcode) %><br/>
  <%= submit_tag "Enter the edildo world", class: 'btn btn-large btn-primary'%>
<% end %>
</div>

app/views/userdetails/mainshow.html.erb
Welcome to the world of <strong><%= @userdetail.firstname + " " + @userdetail.lastname%></strong>. <br/>

<% if false %>
	URL passcode: <%= params[:passcode] %> <br/>
	User generated passcode: <%= @userdetail.passcode %> <br/>
<% end %>

<br/><br/>

<%= button_to('On', @userdetail.url + '?value=1', :method => "post", :remote => true, :disable_with => 'loading...') %>	
<%= button_to('Off', @userdetail.url + '?value=0', :method => "post", :remote => true, :disable_with => 'loading...') %>	

app/views/userdetails/new.html.erb
<div class="well well-large">
	welcome... <%= current_user.email %><br/><br/>

	<div class="alert alert-info">	
		Update your information...Don't worry it's safe with us.
	</div>	

	 <%= form_for @userdetail do |f| %>
		<% if @userdetail.errors.any? %>
			<div class="alert alert-error">
				<%= @userdetail.errors.full_messages.join("<br/>").html_safe %>
			</div>
		<% end %>

		<div class="row-fluid">	
			<%= f.label :firstname, "FIRST NAME:" %>
			<%= f.text_field :firstname, class: "span3", placeholder: "First Name" %><br/>
			
			<%= f.label :lastname, "LAST NAME:" %>
			<%= f.text_field :lastname, class: "span3", placeholder: "Last Name" %><br/>
		
			<%= f.submit "Create your profile!", class: "btn btn-large btn-primary" %>
		</div>	
	<% end %>

</div>
  		

app/views/userdetails/show.html.erb
<% if @userdetail.url.nil? or @userdetail.url == "" %>
	<div class="well well-small">
		A device is not been allocated yet. Contact admin to allocate a device to you.
	</div>	
<% else %>
	<div class="well well-small">
		<!--Welcome to the world of <strong><%= @userdetail.firstname + " " + @userdetail.lastname%></strong>. <br/>-->
		Welcome to teledildonics access page!<br/>
		Play around with the buttons below to change the speed of <%= @userdetail.firstname %>'s edildo.
	</div>
	<div class="well well-small">

		<%= button_to "Switch-On", userdetail_button_action_path(@userdetail, :value => "1"), :method => "post", :remote => true, :disable_with => 'loading...', :class => "btn btn-large btn-primary btn-success" %>

		<%= button_to "Speed-2", userdetail_button_action_path(@userdetail, :value => "2"), :method => "post", :remote => true, :disable_with => 'loading...', :class => "btn btn-large btn-primary btn-info" %>

		<%= button_to "Speed-3", userdetail_button_action_path(@userdetail, :value => "3"), :method => "post", :remote => true, :disable_with => 'loading...', :class => "btn btn-large btn-primary btn-info" %>

		<%= button_to "Speed-4", userdetail_button_action_path(@userdetail, :value => "4"), :method => "post", :remote => true, :disable_with => 'loading...', :class => "btn btn-large btn-primary btn-info" %>

		<%= button_to "Speed-5", userdetail_button_action_path(@userdetail, :value => "5"), :method => "post", :remote => true, :disable_with => 'loading...', :class => "btn btn-large btn-primary btn-info" %>

		<%= button_to "Speed-6", userdetail_button_action_path(@userdetail, :value => "6"), :method => "post", :remote => true, :disable_with => 'loading...', :class => "btn btn-large btn-primary btn-info" %>

		<%= button_to "Switch-Off", userdetail_button_action_path(@userdetail, :value => "0"), :method => "post", :remote => true, :disable_with => 'loading...', :class => "btn btn-large btn-primary btn-danger" %>

	</div>

<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>